### ISSUE TITLE
Change layout from grid to flexbox for inline form labels

### ISSUE THREAD

**Issue by marceickhoff** [marceickhoff/mni#47]
https://github.com/marceickhoff/mni/blob/98653b10adc2e26a1b42a2c49bbf36f300a2c4ff/lib/scss/components/_form.scss#L53-L59

This causes issues with small elements like checkboxes. It should be:

```scss
&.inline-label {
  display: flex;
  align-items: center;

  > *:not(:first-child) {
    margin-left: rhythm(1);
  }
  
  ...
```
